---
version: '2'
services:
  nginx:
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - /static/:/static/
    links:
      - backend

  postgres:
    image: 'papyrus/db'
    build: ./docker/db
    env_file: './envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - /srv/docker/papyrus/postgresql/data/:/var/lib/postgresql/data
      - /srv/docker/papyrus/postgresql/log/:/var/log/postgresql

  backend:
    image: 'papyrus/backend'
    build: .
    env_file: './envs/${DOCKER_COMPOSE_ENV}.env'
    volumes:
      - .:/code
      - /static/:/static/
    ports:
      - '8000:8000'
    depends_on:
      - postgres

