# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 02:04
from __future__ import unicode_literals

import app.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.users.managers.DefaultUserManager()),
            ],
        ),
    ]
